services:
  postgres:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - project_name_postgres_data:/bitnami/postgresql

volumes:
  project_name_postgres_data:
    driver: local
